/** Full task inventory — short titles, minimal notes (email only when needed). */

export const TASKS = [
  // ── URGENT ──
  {
    text: "Apply for Fiktionsbescheinigung — Rödelbergweg",
    due_date: "2026-10-09",
    category: "visa",
    step_order: 1,
    priority: "urgent",
    status: "active",
  },
  {
    text: "Find Frankfurt room — max €400 warm",
    due_date: "2026-07-01",
    category: "visa",
    step_order: 2,
    priority: "urgent",
    status: "active",
  },
  {
    text: "Pay semester fee — €408.28",
    notes: "IBAN DE18 5005 0000 0001 006535 · ref = Matrikelnummer",
    due_date: "2026-07-31",
    category: "study",
    step_order: 3,
    priority: "urgent",
    status: "active",
  },
  {
    text: "Anmeldung — within 14 days of lease",
    category: "visa",
    step_order: 4,
    priority: "urgent",
    status: "active",
  },
  {
    text: "Apply for 3-year residence permit",
    category: "visa",
    step_order: 5,
    priority: "urgent",
    status: "active",
  },
  {
    text: "Reply to Forster — German or English?",
    notes: "forster@nachhaltigkeit.uni-frankfurt.de",
    category: "study",
    priority: "urgent",
    status: "active",
  },
  {
    text: "Confirm Jam Session — send performance details",
    notes: "faustino@hochschulsport.uni-frankfurt.de",
    due_date: "2026-07-01",
    category: "personal",
    priority: "urgent",
    status: "active",
  },
  {
    text: "Close Commerzbank account",
    category: "admin",
    priority: "urgent",
    status: "active",
  },
  {
    text: "Complete Bhavin's task",
    category: "admin",
    priority: "urgent",
    status: "active",
  },

  // ── IMPORTANT ──
  {
    text: "Reply to Prof. Jattana — HiWi extension",
    notes: "jattana@em.uni-frankfurt.de",
    category: "job",
    priority: "important",
    status: "active",
  },
  {
    text: "Activate Goethe-Campus account",
    category: "study",
    priority: "important",
    status: "active",
  },
  {
    text: "Attend job fair — Campus Westend",
    due_date: "2026-06-11",
    category: "job",
    priority: "important",
    status: "active",
  },
  {
    text: "Pass all fundamental exams",
    category: "study",
    priority: "important",
    status: "active",
  },
  {
    text: "Apply for backup universities",
    category: "study",
    priority: "important",
    status: "active",
  },
  {
    text: "Follow up — Prof. Storz",
    notes: "kiradjieva@em.uni-frankfurt.de",
    category: "job",
    priority: "important",
    status: "active",
  },
  {
    text: "Apply for full-time IT jobs",
    category: "job",
    priority: "important",
    status: "active",
  },
  {
    text: "Get B1 German certificate",
    due_date: "2026-08-16",
    category: "study",
    priority: "important",
    status: "active",
  },
  {
    text: "Study Economics daily — aim for 1.0",
    category: "study",
    priority: "important",
    status: "active",
  },
  {
    text: "Mail professors — AT, CH, NL, UK, Scandinavia",
    category: "job",
    priority: "important",
    status: "active",
  },
  {
    text: "Check GROW@Goethe Mentoring OLAT",
    category: "study",
    priority: "important",
    status: "active",
  },
  {
    text: "Prepare English CV (tabular format)",
    category: "job",
    priority: "important",
    status: "active",
  },

  // ── TO-DO ──
  {
    text: "Switch to work visa after full-time job",
    category: "visa",
    priority: "todo",
    status: "active",
  },
  {
    text: "Reach 72 kg",
    due_date: "2026-08-16",
    category: "personal",
    priority: "todo",
    status: "active",
  },
  {
    text: "Junges Forum Demokratie scholarship",
    due_date: "2026-06-30",
    category: "study",
    priority: "todo",
    status: "active",
  },
  {
    text: "Register for ICS workshops",
    notes: "icsrm@tu-darmstadt.de",
    category: "job",
    priority: "todo",
    status: "active",
  },
  {
    text: "Resend English Theatre request",
    notes: "mathilde.charras@english-theatre.de",
    category: "personal",
    priority: "todo",
    status: "active",
  },
  {
    text: "Reply to GStEP photo consent",
    notes: "gstep@uni-frankfurt.de",
    category: "study",
    priority: "todo",
    status: "active",
  },
  {
    text: "Dance Night Hawaii — RSVP",
    notes: "hoffmann@hochschulsport.uni-frankfurt.de",
    due_date: "2026-07-17",
    category: "personal",
    priority: "todo",
    status: "active",
  },
  {
    text: "Decide on LAUNCH Build Days",
    notes: "applications@launch-rm.de",
    category: "job",
    priority: "todo",
    status: "active",
  },
  {
    text: "Respond to Kleinanzeigen buyers",
    category: "admin",
    priority: "todo",
    status: "active",
  },

  // ── COMPLETED ──
  { text: "Build personal task dashboard", priority: "important", status: "done" },
  { text: "Inform Goethe — not going to Rotterdam", priority: "urgent", status: "done" },
  { text: "Reply to professor — student assistant", priority: "important", status: "done" },
  { text: "Email English Theatre — tickets & timesheet", priority: "todo", status: "done" },
  { text: "Compare salary with contract", priority: "important", status: "done" },
  { text: "Follow up with Ramya", priority: "todo", status: "done" },
  { text: "Watch English Theatre shows + notes", priority: "todo", status: "done" },
  { text: "Buy onion, eggs and potato", priority: "todo", status: "done" },
  { text: "Buy sunscreen, facewash, night cream, soap", priority: "todo", status: "done" },
  { text: "Attend FUAS welcome week", priority: "todo", status: "done" },
  { text: "Get English Theatre tickets", priority: "todo", status: "done" },
  { text: "Transfer money to Jemmy and Hasnain", priority: "todo", status: "done" },
  { text: "Transfer insurance payment", priority: "important", status: "done" },
  { text: "Ask Lucas about HiWi + mail professors", priority: "important", status: "done" },
  { text: "Email Lucas and Prof. Jattana", priority: "important", status: "done" },
];
