/** Full task inventory — short titles, notes, due dates, categories. */

export const TASKS = [
  // ── URGENT ──
  {
    text: "Apply for Fiktionsbescheinigung",
    notes: "Frankfurt Ausländerbehörde, Rödelbergweg. On Bad Vilbel address. Bring: passport, visa, enrollment proof, biometric photo, fee, insurance, housing search evidence.",
    due_date: "2026-10-09",
    category: "visa",
    step_order: 1,
    priority: "urgent",
    status: "active",
  },
  {
    text: "Find accommodation in Frankfurt",
    notes: "Stadtgebiet only, max ~€400 warm, from 1 July. Kleinanzeigen WG lead was deleted 5 June — keep searching.",
    due_date: "2026-07-01",
    category: "visa",
    step_order: 2,
    priority: "urgent",
    status: "active",
  },
  {
    text: "Pay semester fee — €408.28",
    notes: "Rückmeldung WiSe 2026/27. IBAN DE18 5005 0000 0001 006535, BIC HELADEF1, reference = Matrikelnummer. Late fee €30 after 31 Jul.",
    due_date: "2026-07-31",
    category: "study",
    step_order: 3,
    priority: "urgent",
    status: "active",
  },
  {
    text: "Anmeldung at Frankfurt Bürgeramt",
    notes: "Within 14 days of signing your Frankfurt lease. Needed for residence permit.",
    category: "visa",
    step_order: 4,
    priority: "urgent",
    status: "active",
  },
  {
    text: "Apply for 3-year residence permit",
    notes: "Frankfurt Ausländerbehörde. Needs: Anmeldung, enrollment, financial means, health insurance.",
    category: "visa",
    step_order: 5,
    priority: "urgent",
    status: "active",
  },
  {
    text: "Reply to Forster — Green Tea with P",
    notes: "Confirm German or English for conversation with university President. forster@nachhaltigkeit.uni-frankfurt.de",
    category: "study",
    priority: "urgent",
    status: "active",
  },
  {
    text: "Confirm Jam Session performance",
    notes: "Send performance details to Faustino for the programme. Tue 1 July 2026, 18:00–22:00. faustino@hochschulsport.uni-frankfurt.de",
    due_date: "2026-07-01",
    category: "personal",
    priority: "urgent",
    status: "active",
  },
  {
    text: "Close Commerzbank account",
    category: "admin",
    priority: "urgent",
    status: "active",
  },
  {
    text: "Complete Bhavin's task",
    category: "admin",
    priority: "urgent",
    status: "active",
  },

  // ── IMPORTANT ──
  {
    text: "Reply to Prof. Jattana — HiWi extension",
    notes: "Express interest in contract extension. jattana@em.uni-frankfurt.de",
    category: "job",
    priority: "important",
    status: "active",
  },
  {
    text: "Activate Goethe-Campus account",
    notes: "Check next steps for your application. goethe-campus.uni-frankfurt.de",
    category: "study",
    priority: "important",
    status: "active",
  },
  {
    text: "Attend ENTER_ZUKUNFT_WIWI job fair",
    notes: "Thu 11 June 2026, Hörsaalzentrum, Campus Westend.",
    due_date: "2026-06-11",
    category: "job",
    priority: "important",
    status: "active",
  },
  {
    text: "Pass all fundamental exams",
    notes: "Aim for top grades across all subjects.",
    category: "study",
    priority: "important",
    status: "active",
  },
  {
    text: "Apply for backup universities",
    notes: "Low/no-fee, public, English-taught programmes in Germany.",
    category: "study",
    priority: "important",
    status: "active",
  },
  {
    text: "Follow up — Prof. Storz research assistant",
    notes: "Gentle nudge if no reply. kiradjieva@em.uni-frankfurt.de",
    category: "job",
    priority: "important",
    status: "active",
  },
  {
    text: "Apply for full-time IT jobs in Germany",
    category: "job",
    priority: "important",
    status: "active",
  },
  {
    text: "Get B1 German certificate",
    due_date: "2026-08-16",
    category: "study",
    priority: "important",
    status: "active",
  },
  {
    text: "Study Economics daily — aim for 1.0",
    notes: "Daily preparation across all subjects.",
    category: "study",
    priority: "important",
    status: "active",
  },
  {
    text: "Mail professors for research outreach",
    notes: "Austria, Switzerland, Netherlands, UK, Scandinavia. Vienna contact #1 not working — find alternative.",
    category: "job",
    priority: "important",
    status: "active",
  },
  {
    text: "Check GROW@Goethe Mentoring OLAT",
    notes: "Unread announcements from 2 June.",
    category: "study",
    priority: "important",
    status: "active",
  },
  {
    text: "Prepare English CV (tabular format)",
    notes: "Needed for jobs, research roles, and applications.",
    category: "job",
    priority: "important",
    status: "active",
  },

  // ── TO-DO ──
  {
    text: "Switch to work visa after full-time job",
    notes: "Then finish the Master alongside work.",
    category: "visa",
    priority: "todo",
    status: "active",
  },
  {
    text: "Reach 72 kg target weight",
    due_date: "2026-08-16",
    category: "personal",
    priority: "todo",
    status: "active",
  },
  {
    text: "Junges Forum Demokratie scholarship",
    notes: "Deadline via GROW@Goethe OLAT.",
    due_date: "2026-06-30",
    category: "study",
    priority: "todo",
    status: "active",
  },
  {
    text: "Register for ICS Rhein-Main workshops",
    notes: "TU Darmstadt career workshops. icsrm@tu-darmstadt.de",
    category: "job",
    priority: "todo",
    status: "active",
  },
  {
    text: "Resend English Theatre request",
    notes: "To Mathilde Charras — Marina Brunner has left. mathilde.charras@english-theatre.de",
    category: "personal",
    priority: "todo",
    status: "active",
  },
  {
    text: "Reply to GStEP photo consent",
    notes: "Yes/no on March ECB tour group photos. gstep@uni-frankfurt.de",
    category: "study",
    priority: "todo",
    status: "active",
  },
  {
    text: "Dance Night Hawaii — RSVP",
    notes: "Standard & Latein, 17 July 2026. hoffmann@hochschulsport.uni-frankfurt.de",
    due_date: "2026-07-17",
    category: "personal",
    priority: "todo",
    status: "active",
  },
  {
    text: "Decide on LAUNCH Build Days hackathon",
    notes: "applications@launch-rm.de",
    category: "job",
    priority: "todo",
    status: "active",
  },
  {
    text: "Respond to Kleinanzeigen buyers",
    notes: "Birthday-decoration listings — sell or give away.",
    category: "admin",
    priority: "todo",
    status: "active",
  },

  // ── COMPLETED ──
  { text: "Build personal task dashboard", priority: "important", status: "done" },
  { text: "Inform Goethe — not going to Rotterdam", priority: "urgent", status: "done" },
  { text: "Reply to professor — student assistant", priority: "important", status: "done" },
  { text: "Email English Theatre — tickets & timesheet", priority: "todo", status: "done" },
  { text: "Compare salary with contract", priority: "important", status: "done" },
  { text: "Follow up with Ramya", priority: "todo", status: "done" },
  { text: "Watch English Theatre shows + notes", priority: "todo", status: "done" },
  { text: "Buy onion, eggs and potato", priority: "todo", status: "done" },
  { text: "Buy sunscreen, facewash, night cream, soap", priority: "todo", status: "done" },
  { text: "Attend FUAS welcome week", priority: "todo", status: "done" },
  { text: "Get English Theatre tickets", priority: "todo", status: "done" },
  { text: "Transfer money to Jemmy and Hasnain", priority: "todo", status: "done" },
  { text: "Transfer insurance payment", priority: "important", status: "done" },
  { text: "Ask Lucas about HiWi + mail professors", priority: "important", status: "done" },
  { text: "Email Lucas and Prof. Jattana", priority: "important", status: "done" },
];
